apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-platform-suite-component-aeca
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-platform-build-tenant/multi-platform-suite-application-iqnf/multi-platform-suite-component-aeca@sha256:d42fce8d045f9b4937b0f335037cd2b2d0adeb74d9cf244867c47e1075db6d0d
        name: my-go
        resources: {}
status: {}
