apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-platform-suite-component-aeca
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-platform-suite-component-aeca
    app.kubernetes.io/part-of: multi-platform-suite-application-iqnf
  name: multi-platform-suite-component-aeca
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: multi-platform-suite-component-aeca
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: multi-platform-suite-component-aeca
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-platform-build-tenant/multi-platform-suite-application-iqnf/multi-platform-suite-component-aeca@sha256:d42fce8d045f9b4937b0f335037cd2b2d0adeb74d9cf244867c47e1075db6d0d
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
